#!/bin/bash
PLACE=${HOME}/local/lib

extension=$1
name=$2
title=$3

echo "Processing $name with extension $extension"

if [ -f $name.html ]; then
   rm $name.html
fi
if [ -f $name.md ]; then
   rm $name.md
fi

case $extension in
     mlsp) echo "A lisp file! Hmmmmm :)" 
           sbcl --dynamic-space-size 2000 --core $PLACE/mlisp.core \
                --script $PLACE/markdown.lisp $name.mlsp $name.md 
           ;;
     msc) scala -cp $4 $PLACE/markdown.scala $name.msc > $name.md
          ;;
     mpy) python3 $PLACE/markdown.py $name.mpy $name.md
          ;;
     mclj) clj -J-Xmx5g -J-Xms5g -J-Xss1g -Mmain $PLACE/markdown.clj $name.mclj $name.md
           ;;
esac
if [ -f $name.md ]; then
   pandoc -s -f markdown -t html --mathjax --highlight-style=tango \
          --css $PLACE/mlisp.css --metadata title="$title" \
          -o $name.html $name.md
   echo -e "\n\n" >> $name.md
   echo "::: {#footer}" >> $name.md
   echo "[" $(date  +"%B %d, %Y %r") "]{#timestamp}" >> $name.md
   echo ":::" >> $name.md
fi

cat $name.md
